---
title: "ms_3"
author: "John Mark Ozaeta"
date: "2/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(readxl)
library(janitor)
library(readr)
library(ggplot2)

#get inequality data. May be able to explain fluctuations in happiness. also compare difference between gdp per capita and median income.


#Find freedom index, free press. Average number of children

gun_deaths <- read.csv("raw-data/gun_deaths2.csv")%>%
  clean_names()%>%
  rename(country_name = location)%>%
  group_by(country_name)%>%
  summarise(total_deaths = sum(val))



education <- read.csv("raw-data/education2.csv")%>%
  clean_names()

cost_of_living <- read_csv("raw-data/cost_of_living.csv")%>%
  clean_names()%>%
  rename(country_name = name)%>%
  select(country_name, cost_of_living_index)

happiness <- read.csv("raw-data/data.csv")%>%
  clean_names()%>%
  rename(country_name = name)

gdpPerCapita <- readxl::read_xls("raw-data/gdp.xls", skip = 3)%>%
  clean_names()

urbanization <- readxl::read_xls("raw-data/urbanization.xls", skip =3)%>%
  clean_names()%>%
  rename(urbanization = x2018)%>%
  select(country_name, urbanization)

gdpPerCapita2 <- gdpPerCapita%>%
  select(country_name, country_code, x2018)

HFI <- read.csv("raw-data/hfi_2018.csv")%>%
  clean_names()%>%
  mutate(myyear = max(year))%>%
  filter(year == myyear)%>%
  select(iso_code, region, hf_score, pf_score, ef_score)%>%
  rename(country_code = iso_code)


gini <- read.csv("raw-data/gini.csv")%>%
  clean_names()
  
clean_gini <- gini%>%
  group_by(country_code)%>%
  mutate(myyear = max(year))%>%
  filter(year == myyear)%>%
  select(country_code, value)%>%
  rename(gini_index = value)


fertility_rate <- read.csv("raw-data/fertility.csv", skip =3)%>%
  clean_names()%>%
  select(country_code, x2018)%>%
  rename(fertility_rate = x2018)

life_expectancy <- read.csv("raw-data/expectancy.csv", skip =3)%>%
  clean_names()%>%
  select(country_code, x2018)%>%
  rename(life_expectancy = x2018)

view(life_expectancy)  
#chrstgenpct, judgenpct, islmgenpct, budgenpct, zorogenpct, hindgenpct, #sikhgenpct, shntgenpct, )

religion <- readxl::read_xlsx("raw-data/Religious_Composition_by_Country_2010-2050.xlsx", sheet =   "rounded_percentage")%>%
  filter(Year == 2010)%>%
  select(Country, Unaffiliated)%>%
  mutate(nonreligpct = as.numeric(Unaffiliated))%>%
  mutate(religpct = 100 - nonreligpct, country_name = Country)%>%
  select(country_name, religpct, nonreligpct)



master1 <- happiness%>%
  full_join(gdpPerCapita2)


cleaned <- read_csv("raw-data/troubleshoot1.csv")

cleaned1 <- cleaned%>%
  filter(is.na(x2018))%>%
  select(country_name, country_code)%>%
  left_join(gdpPerCapita2, by = "country_code")%>%
  select(country_name.x, country_code, x2018)%>%
  rename(country_name = country_name.x)

master <- cleaned%>%
  filter(!is.na(x2018))%>%
  full_join(cleaned1)%>%
  filter(!is.na(happiness_rank))

master <- master%>%
  left_join(cost_of_living, by = "country_name")

master <- master%>%
  left_join(HFI, by = "country_code")

master <- master%>%
  left_join(clean_gini, by = "country_code")

master <- master%>%
  left_join(religion, by = "country_name")

master <- master%>%
  left_join(gun_deaths, by = "country_name")

master <- master%>%
  left_join(fertility_rate, by = "country_code")

master <- master%>%
  left_join(life_expectancy, by = "country_code")

view(master)
```


ggplot(master, aes(x = data, y = happiness_score)) +geom_point() + wrap +
           labs(x = input$var, y = "Happiness Score from 0-10") + theme_classic()





```{r}
ggplot(master, aes(x = pf_score, y = happiness_score))+
  geom_point()+
  geom_smooth(method = "lm")

ggplot(master, aes(x = ef_score, y = happiness_score))+
  geom_point()+
  geom_smooth(method = "lm")

ggplot(master, aes(x = hf_score, y = happiness_score, color = region))+
  geom_point()+
facet_wrap("region")+
  geom_smooth(method = "lm")

ggplot(master, aes(x =x2018, y = hf_score, color = region))+
  geom_point()+
  scale_x_log10()+
  geom_smooth(method = "lm")

ggplot(master, aes(x = gini_index, y = happiness_score))+
  geom_point()+
  geom_smooth(method = "lm")

ggplot(master, aes(x = religpct, y = happiness_score))+
   geom_point()+
  geom_smooth(method = "lm")

ggplot(master, aes(x = x2018, y = happiness_score, color = region))+
  geom_point()+
  scale_x_log10()

ggplot(master, aes(x = total_deaths, y = happiness_score))+
  geom_point()+
  scale_x_log10()

ggplot(master, aes(x = fertility_rate, y = happiness_score))+
  geom_point()+
  geom_smooth(method ="lm")

ggplot(master, aes(x = life_expectancy, y = happiness_score))+
  geom_point()

ggplot(master, aes(x = x2018, y = life_expectancy))+
  geom_point()+
  scale_x_log10()

```

